SELECT 
	  T.TABLE_NAME AS Tabla
	, C.COLUMN_NAME AS Columna
	, C.IS_NULLABLE AS Nulo
	, C.DATA_TYPE AS Tipo
	, isnull(C.CHARACTER_MAXIMUM_LENGTH, 0) AS Longitud 
	, 	CASE 
		WHEN lower(C.DATA_TYPE) IN ('varchar','nvarchar') THEN 
			C.COLUMN_NAME + ' ' + UPPER(C.DATA_TYPE) + '(' + CAST(ISNULL(C.CHARACTER_MAXIMUM_LENGTH, 0) AS VARCHAR) + ')'
		WHEN lower(C.DATA_TYPE) IN ('decimal') THEN 
			C.COLUMN_NAME + ' ' + UPPER(C.DATA_TYPE) + '(10,2)'
		ELSE
			CASE 
			WHEN C.COLUMN_NAME = 'id' THEN 
				C.COLUMN_NAME + ' ' + UPPER(C.DATA_TYPE) + ' IDENTITY CONSTRAINT PK_' + T.TABLE_NAME + ' PRIMARY KEY'
			WHEN C.COLUMN_NAME LIKE 'id_%' THEN 
				C.COLUMN_NAME + ' ' + UPPER(C.DATA_TYPE) + ' CONSTRAINT FK_' + T.TABLE_NAME + '_' + RIGHT(C.COLUMN_NAME,len(C.COLUMN_NAME)-3) + ' FOREIGN KEY (' + C.COLUMN_NAME + ') REFERENCES ' + RIGHT(C.COLUMN_NAME,len(C.COLUMN_NAME)-3) + ' (id)'
			ELSE 
				C.COLUMN_NAME + ' ' + UPPER(C.DATA_TYPE)
			END 
		END AS ColumnaDefinicion
FROM 
	INFORMATION_SCHEMA.tables T 
	INNER JOIN INFORMATION_SCHEMA.columns C ON T.TABLE_NAME = C.TABLE_NAME 
WHERE 
	T.TABLE_NAME NOT IN ('sysdiagrams')
	AND T.TABLE_TYPE = 'BASE TABLE'
ORDER BY 
	T.TABLE_NAME, C.ORDINAL_POSITION